jasypt:
  encryptor:
    bean: jasyptStringEncryptor

spring:
  profiles:
    active: local

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    platform: mysql

github:
  client-id: ENC(CN9dc5xrwzXTcSNKOnjifTjAEW5egizN3sYsayrFRMXbcv17zTsK+2GmUFqpAi4sjSfPPM8BGIQXUE3q+Ex6XA==)
  client-secret: ENC(YVWRlAETZ49LxvmkzrNiOD4r3QRZP4s1N75Q/4wNqOl5dS7Mlhs2HanYj4uhDSG+8RhXMr0inK2AjMgP/JzKm0V2CiT15e+j/uuQ7NSSP5o=)
  user-api-url: https://api.github.com/user
  access-token-url: https://github.com/login/oauth/access_token

jwt:
  key: ENC(t/LBsuV02orfhLkLcskNxkpW63AY+ypsWISnMjrAeTcNOzSSi0MOJbhKAGF/DZLX)

debug: true

---
spring:
  profiles: local

  datasource:
    initialization-mode: never
    url: ENC(tRrIOp5nO55N8q8Qq6Xdc4Fhatvl85mCaQFhijS5twYeescFDu7v+nsgzcA0gocbirAn/1d3cRPXZT5rCBIFqq3XYe9pNjmLfggyRiBrYQ88A07VddGPAHoAK9WiWj7yXqjh+bz9LY4Bo3V0jIIJSQ==)
    username: ENC(AgBSwFOGKfOukj5tDRbSX/Q0M1fKgaBtB7mGaqgRwdhsYFZpVqYq3Qh5WL9ZehQN)
    password: ENC(AFdKnEr2z3Ds8rIhtfR6oHJ3BRFiFI4UJf19C0WjqCLSPgZXQzZ7+lydv3toRfvj)

logging:
  level:
    sql: debug

---
spring:
  profiles: real_server

  datasource:
    url: ENC(yk6nCnR2XyVGeFSQmh465FDJr7jWedMatu17MnzSGI2TFTdKyc/Llvhu3k68P6oMQHTw4aG5w8MxEaM1WW6urtNO/4t2Sb1gNlUiL98sJCJykLCUdwjk2VrQ8h2OUK27U6voRk/iMVWxEERwACLQOw==)
    username: ENC(wamnpgKFwmO2cjfbvOyyTo4lAClyOtVcmGWVtSOyUID2pslv8PEGVDRFw0yQdz87)
    password: ENC(jyYd6+exdGhjXtY3GmYqX8P11HFl8wUbGPp8JR+7x27vdK7TmKhMVMHMv+4tsRWF)